spring:
  application:
    name: scheduleevent

  docker:
    compose:
      enabled: false

  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}

server:
  port: 8082

api:
  security:
    token:
      secret: ${SECURITY_JWT_SECRET}
